version: '3'

services:
   rtl433: 
        image: weatherhass/rtl_433
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        volumes:
            - /usr/local/Podman/DockerCompose/rtl_433/rtl_433.conf:/etc/rtl_433/rtl_433.conf
        devices:
            - "${DEVICE}"
        entrypoint: /root/runme.sh
